### ISSUE TITLE
Code does not running

### ISSUE THREAD

**Issue by SumitG28** [subhanSahebShaik/detectify#1]
Codes is setup easily 
but after i upload deep fake video is show error can you tell me how to resolved this problem sir or which type of video i give to output please guide me

**Comment by subhanSahebShaik** [comment]
Hello @SumitG28,
Thanks for using and reaching me out. But I couldn't help you out without knowing the issue clearly. Could please attach any screenshot or explan the error clearly. And just now I updated readme.md about models. It also might be a reason for your issue. Try it out and please let me know if the issue still persists.

**Comment by SumitG28** [comment]
![IMG-20240513-WA0008](https://github.com/subhanSahebShaik/detectify/assets/148853060/002e606c-ebbf-47f8-ba1e-80c91cf76061)
![IMG-20240513-WA0008](https://github.com/subhanSahebShaik/detectify/assets/148853060/0bbd59a4-3885-474d-b544-c42326f2dae5)

**Comment by SumitG28** [comment]
I think some file are missing from this projects that  why this error come after upload video of deepfake

**Comment by SumitG28** [comment]
![IMG-20240513-WA0006](https://github.com/subhanSahebShaik/detectify/assets/148853060/5fc7941e-b9ee-4122-80c1-455157e7df3c)
Project is work but after i upload video deepfake then it will show error

**Comment by SumitG28** [comment]
Ok sir i check readme and try again

**Comment by subhanSahebShaik** [comment]
Yeah, I think I forgot to add something. There should be 2 empty 'uploaded_videos' and 'uploaded_images' folders at root directory to store the data we uploaded and the models folder with the downloaded models to get prediction. Please let me know if issue persists after trying this.

**Comment by SumitG28** [comment]
Now its running but  i want deepfake video as a input sir can you tell me where i get this kinds of video, when i upload deep fake video but it says it real video 😅. But i upload deepfake video
![IMG-20240513-WA0011](https://github.com/subhanSahebShaik/detectify/assets/148853060/8d07a270-e215-4c50-aeee-7f8976c2cefa)
![Uploading IMG-20240513-WA0011.jpg…]()

Sir can you tell that which type of video format will support and also final output test image is not show you can see
 Provide me which type of video format i use sir

**Comment by subhanSahebShaik** [comment]
https://github.com/subhanSahebShaik/detectify/assets/122206043/7003b810-0d56-4017-b7d2-4003cc6ef7ba


https://github.com/subhanSahebShaik/detectify/assets/122206043/f56c368a-daab-4c0c-bde2-bbf03e41149e

We used the above videos in our case. These are in .mp4 format within 100MB. And the models may not predict always correct, try with higher sequence length, you might get expected results. And in the result page, the accuracy should be a floating point number. We rendered it from model name, from the models folder. If everything is fine, the cropped images and video also visible in result page. Anyway try with above DeepFakes and also try with different sequence lengths. Especially in my test cases, Sri Ram's video will be get predicted with 20 sequence length, but Sachin's video needs 40 sequence length.

**Comment by SumitG28** [comment]
Sir what is 20 sequence length and 40 sequence length is that video timing sir can your provide documentation for this project so that i learn how project actually work with diagram and what you import modules and etc..
 And thanksyou for your guidance 🙏🙏🙏 you provide good learning

**Comment by subhanSahebShaik** [comment]
Sequence length is nothing but the number of frames considering from the video to extract faces and perform classification. When sequence length is 20, 20 frames from video are considered. So, higher sequence length means high frames to classify which may results better classification. And the documentation is provided in the PDF in the same repo, it's documentation that we prepared for our BTech project review, I think it might help you. If you need anything else feel free to ask. Thank you 😊.

**Comment by SumitG28** [comment]
![IMG-20240514-WA0002](https://github.com/subhanSahebShaik/detectify/assets/148853060/95c34744-d4a0-4981-b658-a9c9ce8af3cd)
I upload shree rama video but it not show frame in the output

**Comment by subhanSahebShaik** [comment]
You're supposed to get the images. I could help, if you attach screenshot of console from Developer tools/Inspect (Ctrl + Shift+ I). And it's not only the issue, accuracy is also not rendering correctly.

**Comment by SumitG28** [comment]
I use linux system show it think page is not load that is the reason
 And here is the screenshot of console screenshot for accuracy is not
correct

**Comment by subhanSahebShaik** [comment]
If you observe the code in views.py,

> request.session["accuracy"] = model_name.split("\\")[-1][6:8]
> request.session["decimal"] = model_name.split("\\")[-1][13:15]

I just rendered the accuracy from model name, which we got from the models folder. Make sure the model names are correct and the names are rendering fine, then the accuracy will be rendered good. And I am unable to see the screenshot of the console that you sent, I didn't get the reason of Linux but if you are able to solve it out, it's very happy.

![image](https://github.com/subhanSahebShaik/detectify/assets/122206043/5ccd62c9-d43f-43a0-8c7a-5f77ea60e86a)

**Comment by SumitG28** [comment]
![IMG-20240514-WA0009](https://github.com/subhanSahebShaik/detectify/assets/148853060/4d305cd4-fa6f-481c-bebb-39b856374dcf)
![IMG-20240514-WA0008](https://github.com/subhanSahebShaik/detectify/assets/148853060/71258370-65cb-45bc-9aca-78b40810a6dc)
![IMG-20240514-WA0007](https://github.com/subhanSahebShaik/detectify/assets/148853060/63a4105b-46b9-426f-b8a5-ae0fe7a70100)
![IMG-20240514-WA0006](https://github.com/subhanSahebShaik/detectify/assets/148853060/9cea78ac-70e5-44c4-961e-8799baef29e8)
Here is the console screenshot sir
Okk i check model name and code after that i contact you thankyou for your support😊🙏

**Comment by subhanSahebShaik** [comment]
![image](https://github.com/subhanSahebShaik/detectify/assets/122206043/e4616a12-f8b9-48e0-84ea-779beb27c7d5)

I think the above line is making the things wrong. The line works fine for WIndows paths, but incase of Linux the path doesn't appear to have the \\ (Double Back Slash).
So, to solve this images issue you may try to crop the file name as,

> video_file_name = video_file.split('/')[-1]

I think it might work for your system. Based on that only, the video name

> video_file_name_only = video_file_name.split('.')[0]

and image name

> image_name = video_file_name_only+"_preprocessed_"+str(i)+'.png'

are getting assigned. So, try to get the video name with different strategy based on the file path. I think it should solve the problem. And don't call me Sir, just Subhan. I am a BTech final year student, who just completed his final year exams and working as an Intern.

**Comment by SumitG28** [comment]
![IMG-20240514-WA0016](https://github.com/subhanSahebShaik/detectify/assets/148853060/e2c7e64e-966c-42f2-8134-3af8cbf4e74a)
Accuracy is not show properly frame problem solved

**Comment by subhanSahebShaik** [comment]
![image](https://github.com/subhanSahebShaik/detectify/assets/122206043/21878aaf-7fab-4aab-88af-f320edbf2833)

The confidence is computed everytime but not the accuracy. The possible accuracies are,

84.10
87.20
90.20
90.60
93.10
95.40
97.60
97.80
97.10

Actually these are not the accuracies, these are the things that we designed ourselves to satisfy my college staff during project review. We just wanted to show them accuracy over 85%. Actual accuracies are in model names like model 84 accuracy with 10 frames sequence length, from this we rendered 84.10. And for the above video try with 40 sequence length, it should get prediction as Fake the video is a deep fake one. I am very happy that the application is finally running successfully. If you don't have any problems we could close this issue for now, but please don't hesitate to contact me if you're facing any difficulties.

And also for documentation and clear idea about this project, I encourage you to visit https://github.com/abhijitjadhav1998/Deepfake_detection_using_deep_learning repository. This is the original repository that helped me to work out the application.

And also I would like to introduce the unique feature of my project, API access. Please try this feature out from your Linux machine with a curl command, the syntax is available in homepage of the web application.

**Comment by subhanSahebShaik** [comment]
[image: image]
<https://private-user-images.githubusercontent.com/122206043/330415169-21878aaf-7fab-4aab-88af-f320edbf2833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTA2MTMsIm5iZiI6MTcxNTc1MDMxMywicGF0aCI6Ii8xMjIyMDYwNDMvMzMwNDE1MTY5LTIxODc4YWFmLTdmYWItNGFhYi04OGFmLWYzMjBlZGJmMjgzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwNTE4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGRlYWZhM2RhNDU1Njk3NmE1MjkwZTUwZjY1OWM4NDI5MTc2NTVjMDRmYzBiZTYzODI0NDVkNGNhZDQwYmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AfX5Zh_-YJGDzdFpQnIwTstnEh97mqoXSAUFymjotYA>

The confidence is computed everytime but not the accuracy. The possible
accuracies are,

84.10
87.20
90.20
90.60
93.10
95.40
97.60
97.80
97.10

Actually these are not the accuracies, these are the things that we
designed ourselves to satisfy my college staff during project review. We
just wanted to show them accuracy over 85%. Actual accuracies are in model
names like model 84 accuracy with 10 frames sequence length, from this we
rendered 84.10. And for the above video try with 40 sequence length, it
should get prediction as Fake the video is a deep fake one. I am very happy
that the application is finally running successfully. If you don't have any
problems we could close this issue for now, but please don't hesitate to
contact me if you're facing any difficulties.

And also for documentation and clear ideas about this project, I encourage
you to visit
https://github.com/abhijitjadhav1998/Deepfake_detection_using_deep_learning
repository.
This is the original repository that helped me to work out the application.

And also I would like to introduce the unique feature of my project, API
access. Please try this feature out from your Linux machine with a curl
command, the syntax is available in homepage of the web application.

**Comment by SumitG28** [comment]
![IMG-20240514-WA0021](https://github.com/subhanSahebShaik/detectify/assets/148853060/fef0658d-6e01-4532-939d-ef35ccce9537)
Now its working 👍👍👍 totally no issue its fine
Can i close with comment

**Comment by subhanSahebShaik** [comment]
Yeah, sure! It seems everything is good. Now we are ready to close this issue. Thanks for reviewing my work. I am very happy to have raised this issue and made some fixes to the setup steps. Thank you!.
